### ISSUE TITLE
No Http logs are available

### ISSUE THREAD

**Issue by marezelej** [laravel/vapor-ui#35]
- Vapor UI Version: 1.0.0
- Laravel Version: 7.20.0
- PHP Version: 7.4
- Database Driver & Version: Mysql

### Description:
Since we updated laravel-ui to 1.0.0 we are no longer capable of listing the Http logs in vapor-ui. We can see logs on Queue and Console screens, but Http screen is simply empty. We can see old logs (previous to the update). We can see our logs in AWS cloudwatch.

### Steps To Reproduce:
1. Update to 1.0.0
2. Log in http request
3. Look for new logs in Htttp vapor ui

**Comment by nunomaduro** [comment]
@marezelej You don't have a button that says "click here to keep searching"?

**Comment by marezelej** [comment]
@nunomaduro yes, but it does not load anything. Could you explain the expected behaviour of the button please?

**Comment by nunomaduro** [comment]
That's intentional. The previous version was endlessly poll for new results from the CloudWatch API and that often can result in a 502 due to the rate limit applied by AWS.

This package is meant for people getting started with Vapor, or for applications with a few log records in CloudWatch. For a better logging experience, you need to use something like BugSnag or Flare.

**Comment by marezelej** [comment]
I confirm. After many "keep searching" clicks I got the results. Thank you!
